export const courses = [
  { id: "ingles", name: "Introdução à Língua Inglesa", category: "Idiomas", professor: "Luiz", age: "Kids · 8–11 anos", days: "Segunda e quarta · Terça e quinta", time: "09h–10h · 14h–15h", schedules: ["Segunda e quarta · 09h–10h", "Terça e quinta · 14h–15h"], text: "Conversas e prática para ampliar possibilidades.", description: "Um primeiro contato com a língua inglesa de forma leve, prática e conectada ao dia a dia.", learning: "Vocabulário, conversação, compreensão e confiança para se comunicar." },
  { id: "apps", name: "Criação de Aplicativos", category: "Tecnologia", professor: "Luiz", age: "A partir de 15 anos", days: "Segunda e quarta · Terça e quinta", time: "10h–11h · 15h–16h", schedules: ["Segunda e quarta · 10h–11h", "Terça e quinta · 15h–16h"], text: "Do problema à primeira ideia de aplicativo.", description: "Transforme uma ideia em um projeto digital, criando tanto sites quanto aplicativos.", learning: "Ideação, prototipação, lógica de programação, criação de interfaces, sites e aplicativos." },
  { id: "teens", name: "Inclusão Digital 60+", category: "Informática", professor: "Breno", age: "Melhor idade · 60+ anos", days: "Terça e quinta", time: "11h–12h", schedules: ["Terça e quinta · 11h–12h"], text: "Tecnologia, criatividade e autonomia digital para a melhor idade." },
  { id: "robotica", name: "Robótica", category: "Tecnologia", professor: "Breno", age: "Kids · 8–11 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "14h–15h · 10h–11h", schedules: ["Segunda e quarta · 14h–15h", "Terça e quinta · 10h–11h"], text: "Eletrônica, lógica e projetos que ganham movimento.", description: "Aprendizado mão na massa para explorar tecnologia, criatividade e resolução de problemas.", learning: "Eletrônica básica, lógica, programação e construção de projetos com movimento." },
  { id: "games", name: "Desenvolvimento de Games", category: "Tecnologia", professor: "Breno", age: "Kids · 8–11 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "15h–16h · 16h–17h · 09h–10h", schedules: ["Segunda e quarta · 15h–16h", "Segunda e quarta · 16h–17h", "Terça e quinta · 09h–10h"], text: "Roteiro, lógica e criação do seu primeiro jogo.", description: "Um espaço para imaginar, criar e programar jogos do zero usando o Clickteam Fusion.", learning: "Roteiro, lógica, programação, design de fases e criação de jogos com o Clickteam Fusion." },
  { id: "informatica18", name: "Introdução à Informática", category: "Informática", professor: "Breno ou Luiz", age: "Adultos · 18–59 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "17h–18h · 17h–18h · 11h–12h · 16h–17h", schedules: ["Segunda e quarta · 17h–18h · Adultos", "Terça e quinta · 17h–18h · Adultos", "Segunda e quarta · 11h–12h · Teens", "Terça e quinta · 16h–17h · Teens"], text: "Ferramentas digitais para estudo, trabalho e autonomia.", description: "Aprenda a usar as principais ferramentas digitais para estudar, trabalhar e organizar sua rotina.", learning: "Word, PowerPoint, Excel, criação e organização de pastas e arquivos." },
  { id: "informatica60", name: "Inclusão Digital 60+", category: "Inclusão digital", professor: "Breno", age: "60 anos ou mais", days: "Terça e quinta", time: "11h–12h", schedules: ["Terça e quinta · 11h–12h"], text: "Mais autonomia para explorar o mundo digital." },
  { id: "musica", name: "Música", category: "Cultura", professor: "Edmilson", age: "9–17 anos", days: "Segunda e quarta", time: "14h–15h ou 15h–16h", schedules: ["Segunda e quarta · 14h–15h", "Segunda e quarta · 15h–16h"], text: "Educação musical, escuta e criação coletiva." },
];
