export const courses = [
  { id: "ingles", name: "Introdução à Língua Inglesa", category: "Idiomas", age: "Kids · 8–11 anos", days: "Segunda e quarta · Terça e quinta", time: "09h–10h · 14h–15h", schedules: ["Segunda e quarta · 09h–10h", "Terça e quinta · 14h–15h"], text: "Conversas e prática para ampliar possibilidades.", description: "Um primeiro contato com a língua inglesa de forma leve, prática e conectada ao dia a dia.", learning: "Vocabulário, conversação, compreensão e confiança para se comunicar." },
  { id: "apps", name: "Criação de Aplicativos", category: "Tecnologia", age: "A partir de 15 anos", days: "Segunda e quarta · Terça e quinta", time: "10h–11h · 15h–16h", schedules: ["Segunda e quarta · 10h–11h", "Terça e quinta · 15h–16h"], text: "Do problema à primeira ideia de aplicativo.", description: "Transforme uma ideia em um projeto digital, criando tanto sites quanto aplicativos.", learning: "Ideação, prototipação, lógica de programação, criação de interfaces, sites e aplicativos." },
  { id: "robotica", name: "Robótica", category: "Tecnologia", age: "Kids · 8–11 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "14h–15h · 10h–11h", schedules: ["Segunda e quarta · 14h–15h", "Terça e quinta · 10h–11h"], text: "Eletrônica, lógica e projetos que ganham movimento.", description: "Aprendizado mão na massa para explorar tecnologia, criatividade e resolução de problemas.", learning: "Eletrônica básica, lógica, programação e construção de projetos com movimento." },
  { id: "games", name: "Desenvolvimento de Games", category: "Tecnologia", age: "Kids · 8–11 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "15h–16h · 16h–17h · 09h–10h", schedules: ["Segunda e quarta · 15h–16h", "Segunda e quarta · 16h–17h", "Terça e quinta · 09h–10h"], text: "Roteiro, lógica e criação do seu primeiro jogo.", description: "Um espaço para imaginar, criar e programar jogos do zero usando o Clickteam Fusion.", learning: "Roteiro, lógica, programação, design de fases e criação de jogos com o Clickteam Fusion." },
  { id: "informatica18", name: "Introdução à Informática", category: "Tecnologia", age: "Adultos · 18–59 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "17h–18h · 17h–18h · 11h–12h · 16h–17h", schedules: ["Segunda e quarta · 17h–18h · Adultos", "Terça e quinta · 17h–18h · Adultos", "Segunda e quarta · 11h–12h · Teens", "Terça e quinta · 16h–17h · Teens"], text: "Ferramentas digitais para estudo, trabalho e autonomia.", description: "Aprenda a usar as principais ferramentas digitais para estudar, trabalhar e organizar sua rotina.", learning: "Word, PowerPoint, Excel, criação e organização de pastas e arquivos." },
  { id: "informatica60", name: "Inclusão Digital 60+", category: "Tecnologia", age: "60 anos ou mais", days: "Terça e quinta", time: "11h–12h", schedules: ["Terça e quinta · 11h–12h"], text: "Mais autonomia para explorar o mundo digital." },
];

export const saoPedroCourses = [
  { id: "informatica60", name: "Inclusão Digital 60+", category: "Tecnologia", age: "Melhor idade · 60+ anos", days: "Segunda e quarta · Terça e quinta", description: "Tecnologia, criatividade e autonomia digital para a melhor idade.", learning: "Aprenda a usar ferramentas digitais com mais segurança, autonomia e tranquilidade no dia a dia.", schedules: ["Segunda e quarta · 08h–09h · Inclusão Digital 60+", "Terça e quinta · 08h–09h · Inclusão Digital 60+"] },
  { id: "games", name: "Desenvolvimento de Games", category: "Tecnologia", age: "Kids · 8–11 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", description: "Um espaço para imaginar, criar e programar jogos do zero.", learning: "Roteiro, lógica, programação, design de fases e criação de jogos.", schedules: ["Segunda e quarta · 09h–10h · Games Kids A", "Segunda e quarta · 10h–11h · Games Teens A", "Segunda e quarta · 13h–14h · Games Kids C", "Segunda e quarta · 14h–15h · Games Teens C", "Terça e quinta · 09h–10h · Games Kids B", "Terça e quinta · 10h–11h · Games Teens B", "Terça e quinta · 15h–16h · Games Kids D", "Terça e quinta · 16h–17h · Games Teens D"] },
  { id: "ingles", name: "Inglês", category: "Idiomas", age: "A partir de 15 anos", days: "Terça e quinta", description: "Prática de inglês para ampliar possibilidades de estudo, trabalho e comunicação.", learning: "Vocabulário, conversação, compreensão e confiança para se comunicar.", schedules: ["Terça e quinta · 11h–12h · Inglês Teens A", "Terça e quinta · 13h–14h · Inglês Teens B"] },
  { id: "musica", name: "Orquestra", category: "Música", age: "Crianças e jovens", days: "Manhã e tarde", description: "Educação musical, criação coletiva e apresentações para a comunidade.", learning: "Prática musical, escuta, colaboração e desenvolvimento artístico.", schedules: ["Horário a definir · atividades pela manhã", "Horário a definir · atividades à tarde"] },
];
