export const courses = [
  { id: "ingles", name: "Introdução à Língua Inglesa", category: "Idiomas", professor: "Luiz", age: "Kids · 8–11 anos", days: "Segunda e quarta · Terça e quinta", time: "09h–10h · 14h–15h", schedules: ["Segunda e quarta · 09h–10h", "Terça e quinta · 14h–15h"], text: "Conversas e prática para ampliar possibilidades." },
  { id: "apps", name: "Criação de Aplicativos", category: "Tecnologia", professor: "Luiz", age: "A partir de 15 anos", days: "Segunda e quarta · Terça e quinta", time: "10h–11h · 15h–16h", schedules: ["Segunda e quarta · 10h–11h", "Terça e quinta · 15h–16h"], text: "Do problema à primeira ideia de aplicativo." },
  { id: "teens", name: "Informática Teens", category: "Informática", professor: "Luiz", age: "Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "11h–12h · 16h–17h", schedules: ["Segunda e quarta · 11h–12h", "Terça e quinta · 16h–17h"], text: "Tecnologia, criatividade e autonomia digital." },
  { id: "robotica", name: "Robótica", category: "Tecnologia", professor: "Breno", age: "Kids · 8–11 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "14h–15h · 10h–11h", schedules: ["Segunda e quarta · 14h–15h", "Terça e quinta · 10h–11h"], text: "Eletrônica, lógica e projetos que ganham movimento." },
  { id: "games", name: "Desenvolvimento de Games", category: "Tecnologia", professor: "Breno", age: "Kids · 8–11 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "15h–16h · 16h–17h · 09h–10h", schedules: ["Segunda e quarta · 15h–16h", "Segunda e quarta · 16h–17h · Games Kids", "Terça e quinta · 09h–10h · Games Kids"], text: "Roteiro, lógica e criação do seu primeiro jogo." },
  { id: "informatica18", name: "Introdução à Informática", category: "Informática", professor: "Breno", age: "Adultos · 18–59 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "17h–18h", schedules: ["Segunda e quarta · 17h–18h", "Terça e quinta · 17h–18h"], text: "Ferramentas digitais para estudo, trabalho e autonomia." },
  { id: "informatica60", name: "Inclusão Digital 60+", category: "Inclusão digital", professor: "Breno", age: "60 anos ou mais", days: "Terça e quinta", time: "11h–12h", schedules: ["Terça e quinta · 11h–12h"], text: "Mais autonomia para explorar o mundo digital." },
  { id: "musica", name: "Música", category: "Cultura", professor: "Edmilson", age: "9–17 anos", days: "Segunda e quarta", time: "14h–15h ou 15h–16h", schedules: ["Segunda e quarta · 14h–15h", "Segunda e quarta · 15h–16h"], text: "Educação musical, escuta e criação coletiva." },
];
