"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { courses, units, type UnitId } from "./units";

export default function Home() {
  const [unitFilter, setUnitFilter] = useState<"all" | UnitId>("all");
  const [category, setCategory] = useState("Todas");
  const categories = ["Todas", ...Array.from(new Set(courses.map((course) => course.category)))];
  const visibleCourses = useMemo(() => courses.filter((course) => (unitFilter === "all" || course.units.includes(unitFilter)) && (category === "Todas" || course.category === category)), [unitFilter, category]);

  return <main>
    <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
    <header className="header multi-header">
      <Link href="#inicio" className="brand"><span className="brand-mark">CI</span><span>CASA DA<br /><b>INOVAÇÃO</b></span></Link>
      <nav aria-label="Navegação principal"><a href="#casa">A Casa</a><a href="#unidades">Unidades</a><a href="#cursos">Cursos</a><a href="#historia">História</a><a href="#orquestra">Orquestra</a><a href="#localizacao">Contato</a></nav>
      <Link className="button button-small" href="/pre-matricula">PRÉ-MATRÍCULA <span>↗</span></Link>
    </header>

    <section id="inicio" className="hero multi-hero"><div className="hero-copy"><p className="eyebrow">TERESÓPOLIS · RJ · DESDE 2022</p><h1>Casa da <em>Inovação</em><br /><span className="hero-subtitle">agora em dois lugares.</span></h1><p className="hero-text">Cursos gratuitos de tecnologia, idiomas, música e inclusão digital. Escolha a unidade mais perto de você.</p><div className="hero-actions"><Link className="button" href="#unidades">Escolher minha unidade <span>↗</span></Link><Link className="text-link" href="/pre-matricula">Fazer pré-matrícula <span>→</span></Link></div></div><div className="hero-unit-note"><span>2</span><small>unidades<br />para aprender</small></div><div className="scroll-note">↓ <span>role para explorar</span></div></section>

    <div id="conteudo">
      <section id="casa" className="section manifesto multi-manifesto"><div><p className="eyebrow">A MESMA CASA, NOVOS CAMINHOS</p><h2>Um espaço para<br /><em>criar caminhos.</em></h2></div><div className="manifesto-copy"><p><strong>A Casa da Inovação E.F. Therezópolis</strong> amplia sua presença para estar ainda mais perto da comunidade. Beira-Linha e São Pedro compartilham a mesma missão, com cursos, ciclos e equipes organizados por unidade.</p><div className="stats"><div><strong>2</strong><span>unidades</span></div><div><strong>100%</strong><span>gratuito</span></div><div><strong>∞</strong><span>novos caminhos</span></div></div></div></section>

      <section id="unidades" className="section units-section"><div className="section-head"><div><p className="eyebrow">ESCOLHA SEU PONTO DE PARTIDA</p><h2>Qual unidade<br /><em>é para você?</em></h2><p className="section-lead">Duas unidades, uma mesma Casa da Inovação. Veja ciclo, cursos e localização antes de se inscrever.</p></div></div><div className="unit-grid">{units.map((unit) => <article className={`unit-card unit-${unit.id}`} key={unit.id}><div className="unit-card-top"><span>{unit.label}</span><span>0{unit.cycle}º ciclo</span></div><h3>Casa da Inovação<br /><em>{unit.name}</em></h3><p>{unit.description}</p><div className="unit-meta"><strong>{unit.courseIds.length} cursos</strong>{unit.address ? <span>{unit.address}</span> : <span className="pending-data">Endereço em atualização</span>}</div><div className="unit-actions"><Link className="button" href={`/unidades/${unit.slug}`}>Ver unidade <span>↗</span></Link><Link className="text-link" href={`/pre-matricula?unidade=${unit.slug}`}>Fazer inscrição →</Link></div></article>)}</div></section>

      <section id="cursos" className="section courses-section multi-courses"><div className="section-head"><div><p className="eyebrow">CURSOS POR UNIDADE</p><h2>Encontre o curso<br /><em>ideal para você.</em></h2><p className="section-lead">Use os filtros para ver onde cada oportunidade está disponível.</p></div></div><div className="filter-stack"><div className="unit-filter" role="group" aria-label="Filtrar cursos por unidade"><span>Unidade</span><button className={unitFilter === "all" ? "active" : ""} onClick={() => setUnitFilter("all")}>Todas</button>{units.map((unit) => <button className={unitFilter === unit.id ? "active" : ""} key={unit.id} onClick={() => setUnitFilter(unit.id)}>{unit.name}</button>)}</div><div className="course-filters" role="group" aria-label="Filtrar cursos por categoria">{categories.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="course-grid">{visibleCourses.map((course, index) => <article className="course-card" key={course.id}><div className="course-top"><span>0{index + 1}</span><span>{course.category}</span></div><h3>{course.shortName ?? course.name}</h3><p>{course.text}</p><div className="availability"><span>Disponível em</span>{course.units.map((unitId) => <Link href={`/unidades/${unitId}`} key={unitId}>{units.find((unit) => unit.id === unitId)?.name}</Link>)}</div><div className="course-info"><span>{course.age}<br /><b>{course.days ?? "Horários em atualização"}</b></span><Link aria-label={`Ver detalhes de ${course.name}`} href={`/cursos/${course.id}`}>↗</Link></div></article>)}</div>{visibleCourses.length === 0 && <p className="empty-state">Nenhum curso encontrado com esses filtros.</p>}</section>

      <section id="horarios" className="schedule section"><div><p className="eyebrow">ENCONTRE SUA TURMA</p><h2>Nossos cursos,<br /><em>um começo possível.</em></h2><p>Os horários exibidos aqui são os dados vigentes da Beira-Linha. São Pedro terá horários próprios quando forem confirmados.</p><Link className="text-link" href="/pre-matricula">Escolher unidade e fazer Pré-inscrição →</Link></div><div className="schedule-list">{courses.filter((course) => course.units.includes("beira-linha")).slice(0, 6).map((course) => <Link className="schedule-row" href={`/cursos/${course.id}`} key={course.id}><strong>{course.shortName ?? course.name}</strong><span>Beira-Linha</span><span>{course.days}<br /><b>{course.time}</b></span><i>↗</i></Link>)}</div></section>

      <section id="historia" className="history section multi-history"><div className="history-intro"><p className="eyebrow">NOSSA HISTÓRIA</p><h2>Uma ideia<br />que <em>continua<br />crescendo.</em></h2><p>Da origem em Nova Iguaçu à chegada na Beira-Linha, a Casa abre agora um novo capítulo em São Pedro.</p></div><div className="timeline"><div><b>2018</b><span>O conceito nasce em Nova Iguaçu.</span></div><div><b>2022</b><span>A Casa abre suas portas na Beira-Linha.</span></div><div className="current"><b>Hoje</b><span>São Pedro se junta à trajetória da Casa.</span></div></div></section>
      <section id="orquestra" className="orchestra section"><div className="orchestra-visual"><span className="floating-label">CULTURA · SUSTENTABILIDADE · FUTURO</span><div className="music-symbol">♫</div></div><div className="orchestra-copy"><p className="eyebrow">ORQUESTRA SUSTENTÁVEL</p><h2>Quando a criatividade<br />vira <em>música.</em></h2><p>A Orquestra é um projeto da Casa da Inovação que conecta educação musical, cultura e comunidade nas duas unidades.</p></div></section>
      <section className="founder section multi-founder"><div className="founder-copy"><p className="eyebrow">QUEM FAZ A CASA ACONTECER</p><h2><strong>Alex Castellar</strong></h2><p>Nascido e criado na Beira-Linha, Alex transformou sua trajetória em compromisso com educação, tecnologia e inclusão.</p></div><div className="founder-note"><span>Da comunidade para a comunidade.</span><strong>Uma Casa que cresce sem deixar sua origem para trás.</strong></div></section>
      <section id="localizacao" className="location section multi-location"><div className="location-copy"><p className="eyebrow">NOSSAS UNIDADES</p><h2>A Casa está<br /><em>perto de você.</em></h2><p>Escolha uma unidade para conferir o endereço e como chegar.</p></div><div className="location-units">{units.map((unit) => <article className="location-unit" key={unit.id}><div><span>{unit.label}</span><h3>{unit.name}</h3><p>{unit.address ?? "Endereço exato em atualização."}</p></div>{unit.mapsUrl ? <a className="text-link" href={unit.mapsUrl} target="_blank" rel="noreferrer">Como chegar ↗</a> : <span className="pending-data">Maps disponível em breve</span>}{unit.mapEmbedUrl && <iframe className="location-unit-map" title={`Mapa da unidade ${unit.name}`} src={unit.mapEmbedUrl} loading="lazy" />}</article>)}</div></section>
      <section className="closing section"><p className="eyebrow">SEU PRÓXIMO CAPÍTULO</p><h2>Seu próximo aprendizado<br /><em>pode começar aqui.</em></h2><Link className="button" href="/pre-matricula">Fazer pré-matrícula <span>↗</span></Link></section>
    </div>
    <footer><div className="footer-about"><div className="brand"><span className="brand-mark">CI</span><span>CASA DA<br /><b>INOVAÇÃO</b></span></div><p>Educação, tecnologia e oportunidades para jovens e adultos de Teresópolis.</p></div><div className="footer-nav"><p className="footer-label">NAVEGAÇÃO</p><a href="#unidades">Unidades</a><a href="#cursos">Cursos</a><a href="#historia">Nossa história</a><Link href="/pre-matricula">Pré-matrícula</Link></div><div className="footer-contact"><p className="footer-label">ATENDIMENTO</p><span>TELEFONE</span><a href="https://wa.me/5521966907209">(21) 96690-7209</a><span>BEIRA-LINHA</span><p>Rua Beira Linha, 329<br />Teresópolis · RJ</p></div><div className="footer-social"><p className="footer-label">SOCIAL</p><a href="https://www.instagram.com/casadainovacaoteresopolis/">Instagram ↗</a><p>@casadainovacaoteresopolis</p></div><p className="footer-note">Cursos gratuitos para todas as idades.<br />© Casa da Inovação E.F. Therezópolis</p></footer>
  </main>;
}
