"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { courses, saoPedroCourses } from "./data";
import { InlineRegistration } from "./InlineRegistration";

export default function Home() {
  const [filter, setFilter] = useState("Todos");
  const [unit, setUnit] = useState<"beira-linha" | "sao-pedro">("beira-linha");
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => {
    const heroCoursesButton = document.querySelector<HTMLAnchorElement>('.hero-actions a.button[href="#horarios"]');
    const handleHeroCoursesClick = (event: MouseEvent) => {
      event.preventDefault();
      document.getElementById("horarios")?.scrollIntoView({ behavior: "smooth", block: "start" });
      window.history.replaceState(null, "", "#horarios");
    };
    heroCoursesButton?.addEventListener("click", handleHeroCoursesClick);
    return () => {
      heroCoursesButton?.removeEventListener("click", handleHeroCoursesClick);
    };
  }, []);
  const categories = ["Todos", ...Array.from(new Set(courses.map((course) => course.category)))];
  const visible = useMemo(() => filter === "Todos" ? courses : courses.filter((course) => course.category === filter), [filter]);
  return <main><a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
    <header className={`header${menuOpen ? " menu-open" : ""}`}><Link href="#inicio" className="brand" onClick={() => setMenuOpen(false)}><span className="brand-mark">CI</span><span>CASA DA<br/><b>INOVAÇÃO</b></span></Link><button className="menu-toggle" type="button" aria-label={menuOpen ? "Fechar menu" : "Abrir menu"} aria-expanded={menuOpen} onClick={() => setMenuOpen((open) => !open)}><span/><span/></button><nav><a href="#casa" onClick={() => setMenuOpen(false)}>A Casa</a><a href="#horarios" onClick={() => setMenuOpen(false)}>Cursos</a><a href="#historia" onClick={() => setMenuOpen(false)}>História</a><a href="#orquestra" onClick={() => setMenuOpen(false)}>Orquestra</a><a href="#localizacao" onClick={() => setMenuOpen(false)}>Localização</a></nav><a className="button button-small" href="/pre-matricula">PRÉ-INSCRIÇÃO <span>↗</span></a></header>
    <section id="inicio" className="hero"><div className="hero-copy"><p className="eyebrow">TERESÓPOLIS · RJ · DESDE 2022</p><h1>Casa da <em>Inovação</em><br/><span className="hero-subtitle">E. F. Therezópolis.</span></h1><p className="hero-text">Cursos gratuitos de tecnologia, idiomas, música e inclusão digital para todas as idades.</p><div className="hero-actions"><Link className="button" href="#horarios">Conhecer os cursos <span>↗</span></Link><a className="text-link" href="/pre-matricula">Fazer pré-inscrição <span>→</span></a></div></div><div className="hero-art"><div className="orb orb-one"/><div className="orb orb-two"/><div className="hero-card"><span>APRENDER<br/><b>É ABRIR<br/>CAMINHOS</b></span><span className="card-arrow">↗</span></div><div className="grid-lines"/></div><div className="scroll-note">↓ <span>role para explorar</span></div></section>
    <section id="casa" className="section manifesto"><div><p className="eyebrow">O QUE É A CASA?</p><h2>Um espaço<br/>para <em>criar</em><br/><em>caminhos.</em></h2></div><div className="manifesto-copy"><p><strong>Casa da Inovação Estrada de Ferro Therezópolis</strong> é uma escola pública de habilidades digitais localizada no bairro da Beira Linha, em Teresópolis (RJ). O espaço oferece cursos gratuitos de tecnologia, inclusão digital e cidadania para todas as idades.</p><div className="stats"><div><strong>100%</strong><span>gratuito</span></div><div><strong>4+</strong><span>gerações atendidas</span></div><div><strong>∞</strong><span>novos caminhos</span></div></div></div></section>
    <section id="cursos" className="section courses-section"><div className="section-head"><div><p className="eyebrow">CURSOS GRATUITOS</p><h2>Encontre o curso<br/><em>ideal para você.</em></h2><p className="section-lead">Da tecnologia à música, existem oportunidades para todas as idades.</p></div></div><div className="course-filters">{categories.map((category) => <button key={category} className={filter === category ? "active" : ""} onClick={() => setFilter(category)}>{category}</button>)}</div><div className="course-grid">{visible.map((course, index) => <a className="course-card" href={`/cursos/${course.id}`} key={course.id}><div className="course-top"><span>0{index + 1}</span><span>{course.category}</span></div><h3>{course.name}</h3><p>{course.text}</p><div className="course-info"><span>{course.age}<br/><b>{course.days} · {course.time}</b></span><span aria-hidden="true">→</span></div></a>)}</div></section>
    <section id="horarios" className="schedule section"><div><p className="eyebrow">ENCONTRE SUA TURMA</p><h2>Nossos cursos,<br/><em>dias e horários.</em></h2><p>Escolha primeiro a unidade para consultar a grade correta.</p><div className="unit-switcher" role="tablist" aria-label="Escolha a unidade"><button type="button" role="tab" aria-selected={unit === "beira-linha"} className={unit === "beira-linha" ? "active" : ""} onClick={() => setUnit("beira-linha")}>Beira Linha</button><button type="button" role="tab" aria-selected={unit === "sao-pedro"} className={unit === "sao-pedro" ? "active" : ""} onClick={() => setUnit("sao-pedro")}>São Pedro</button></div><p className="unit-address">{unit === "beira-linha" ? "Rua Beira Linha, 329 · Teresópolis" : <>Rua São Pedro, 191, Loja 01 · Teresópolis<br/><strong>Orquestra: atividades pela manhã e à tarde.</strong></>}</p></div>{unit === "beira-linha" ? <div className="schedule-list">{visible.slice(0, 6).map((course) => <a className="schedule-row" href={`/cursos/${course.id}`} key={course.id}><strong>{course.name}</strong><span>{course.age}</span><span>{course.days}<br/><b>{course.time}</b></span><i aria-hidden="true">↗</i></a>)}</div> : <div className="schedule-list">{saoPedroCourses.map((course) => <a className="schedule-row" href={`/cursos/sao-pedro/${course.id}`} key={course.id}><strong>{course.name}</strong><span>{course.age}</span><span className="sao-pedro-schedule-lines">{course.schedules.map((schedule) => <b key={schedule}>{schedule}</b>)}</span><i aria-hidden="true">↗</i></a>)}</div>}</section>
    <section id="historia" className="history section"><div className="history-intro"><p className="eyebrow">NOSSA HISTÓRIA</p><h2>Uma ideia<br/>que <em>voltou</em><br/><em>para casa.</em></h2><p>Da democratização da tecnologia em Nova Iguaçu à criação de novas oportunidades na Beira Linha, a Casa continua crescendo com a comunidade.</p></div><div className="timeline"><div><b>2018</b><span>O conceito nasce em Nova Iguaçu.</span></div><div><b>2019</b><span>Começam as articulações para Teresópolis.</span></div><div className="current"><b>2022</b><span>A Casa abre suas portas na Beira Linha.</span></div><div className="current"><b>Hoje</b><span>Nova unidade é aberta no São Pedro.</span></div></div></section>
    <section className="founder section"><div className="founder-photo"><img src="/imagens/otimizadas/placa.webp?v=imagem-exata" alt="Placa da Casa da Inovação E. F. Therezópolis" /></div><div className="founder-copy"><p className="eyebrow">NOSSO IDEALIZADOR</p><h2><strong>Alex Castellar</strong></h2><p>Nascido e criado na Beira Linha, em Teresópolis, Alex Castellar transformou sua trajetória em compromisso com educação, tecnologia e inclusão.</p><p>Em 2022, Alex Castellar trouxe a Casa da Inovação para Teresópolis e para o seu próprio bairro, a Beira Linha. O projeto nasceu para ampliar o acesso de jovens e adultos a uma formação melhor e de qualidade, com mais preparo para o mercado de trabalho, contato com a inovação e oportunidades de aprendizagem em tecnologia.</p></div></section>
    <section id="orquestra" className="orchestra section"><div className="orchestra-visual"><span className="floating-label">CULTURA · SUSTENTABILIDADE · FUTURO</span><div className="music-symbol">♫</div></div><div className="orchestra-copy"><p className="eyebrow">ORQUESTRA SUSTENTÁVEL</p><h2>Quando a criatividade<br/>vira <em>música.</em></h2><p>Crianças e jovens aprendem, criam e se apresentam em uma experiência que conecta educação musical, cultura, sustentabilidade e comunidade.</p></div></section>
    <section className="gallery gallery-hero section"><div className="gallery-intro"><p className="eyebrow">A CASA ACONTECE</p><h2>Aprender é uma<br/><em>experiência coletiva.</em></h2></div></section>
    <section id="localizacao" className="location section"><div className="location-copy"><p className="eyebrow">VENHA CONHECER</p><h2>A Casa está<br/><em>perto de você.</em></h2><div className="location-address"><strong>Beira Linha</strong><p>Rua Beira Linha, 329<br/>Teresópolis · RJ</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Rua+Beira+Linha+329+Teresopolis+RJ">Abrir no Google Maps <span>↗</span></a></div><div className="location-address"><strong>São Pedro</strong><p>Rua São Pedro, nº 191, Loja 01<br/>São Pedro, Teresópolis · RJ</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=Rua+São+Pedro+191+Loja+01+São+Pedro+Teresópolis+RJ">Abrir no Google Maps <span>↗</span></a></div></div><div className="location-map location-maps"><iframe title="Mapa da unidade Beira Linha" src="https://www.google.com/maps?q=Rua+Beira+Linha,+329,+Teresópolis,+RJ&output=embed" loading="lazy" /><iframe title="Mapa da unidade São Pedro" src="https://www.google.com/maps?q=Rua+São+Pedro,+191,+Loja+01,+São+Pedro,+Teresópolis,+RJ&output=embed" loading="lazy" /></div></section>
    <InlineRegistration /><section className="closing section"><p className="eyebrow">SEU PRÓXIMO CAPÍTULO</p><h2>Seu próximo aprendizado<br/><em>pode começar aqui.</em></h2><a className="button" href="/pre-matricula">Fazer pré-inscrição <span>↗</span></a></section>
    <footer><div className="footer-about"><div className="brand"><span className="brand-mark">CI</span><span>CASA DA<br/><b>INOVAÇÃO</b></span></div><p>Educação, tecnologia e oportunidades para jovens e adultos de Teresópolis.</p></div><div className="footer-nav"><p className="footer-label">NAVEGAÇÃO</p><a href="#casa">A Casa</a><a href="#horarios">Cursos e horários</a><a href="#historia">Nossa história</a><a href="#orquestra">Orquestra</a><a href="/pre-matricula">Pré-inscrição</a></div><div className="footer-contact"><p className="footer-label">ATENDIMENTO</p><span>TELEFONE</span><a href="https://wa.me/5521966907209">(21) 96690-7209</a><span>E-MAIL</span><a href="mailto:casadainovacaoteresopolis@gmail.com">casadainovacaoteresopolis@gmail.com</a><span>ENDEREÇOS</span><p><strong>Beira Linha</strong><br/>Rua Beira Linha, 329<br/>Teresópolis · RJ</p><p><strong>São Pedro</strong><br/>Rua São Pedro, nº 191, Loja 01<br/>São Pedro, Teresópolis · RJ</p></div><div className="footer-social"><p className="footer-label">SOCIAL</p><a href="https://www.instagram.com/casadainovacaoteresopolis/">Instagram ↗</a><p>@casadainovacaoteresopolis</p><small>SEGUIR NO INSTAGRAM →</small></div><p className="footer-note">Cursos gratuitos para todas as idades.<br/>© Casa da Inovação E.F. Therezópolis</p></footer>
  </main>;
}
