export type UnitId = "beira-linha" | "sao-pedro";
export type Course = { id: string; name: string; shortName?: string; category: string; professor?: string; age: string; days?: string; time?: string; schedules?: string[]; text: string; description?: string; learning?: string; units: UnitId[] };
export type Unit = { id: UnitId; name: string; slug: string; label: string; description: string; cycle: number; address?: string; mapsUrl?: string; mapEmbedUrl?: string; contactEmail?: string; courseIds: string[]; accent: "rust" | "moss" };

export const courses: Course[] = [
  { id: "ingles", name: "Introdução à Língua Inglesa", shortName: "Inglês", category: "Idiomas", professor: "Luiz", age: "Kids · 8–11 anos", days: "Segunda e quarta · Terça e quinta", time: "09h–10h · 14h–15h", schedules: ["Segunda e quarta · 09h–10h", "Terça e quinta · 14h–15h"], text: "Conversas e prática para ampliar possibilidades.", description: "Um primeiro contato com a língua inglesa de forma leve, prática e conectada ao dia a dia.", learning: "Vocabulário, conversação, compreensão e confiança para se comunicar.", units: ["beira-linha", "sao-pedro"] },
  { id: "apps", name: "Criação de Aplicativos", category: "Tecnologia", professor: "Luiz", age: "A partir de 15 anos", days: "Segunda e quarta · Terça e quinta", time: "10h–11h · 15h–16h", schedules: ["Segunda e quarta · 10h–11h", "Terça e quinta · 15h–16h"], text: "Do problema à primeira ideia de aplicativo.", description: "Transforme uma ideia em um projeto digital, criando tanto sites quanto aplicativos.", learning: "Ideação, prototipação, lógica de programação e criação de interfaces.", units: ["beira-linha"] },
  { id: "informatica-teens", name: "Informática Teens", category: "Informática", professor: "Breno ou Luiz", age: "Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "11h–12h · 16h–17h", schedules: ["Segunda e quarta · 11h–12h", "Terça e quinta · 16h–17h"], text: "Ferramentas digitais para estudo, criação e autonomia.", units: ["beira-linha"] },
  { id: "robotica", name: "Robótica", category: "Tecnologia", professor: "Breno", age: "Kids · 8–11 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "14h–15h · 10h–11h", schedules: ["Segunda e quarta · 14h–15h", "Terça e quinta · 10h–11h"], text: "Eletrônica, lógica e projetos que ganham movimento.", description: "Aprendizado mão na massa para explorar tecnologia, criatividade e resolução de problemas.", learning: "Eletrônica básica, lógica, programação e construção de projetos.", units: ["beira-linha"] },
  { id: "games", name: "Desenvolvimento de Games", shortName: "Games", category: "Tecnologia", professor: "Breno", age: "Kids · 8–11 anos · Teens · 12–17 anos", days: "Segunda e quarta · Terça e quinta", time: "15h–16h · 16h–17h · 09h–10h", schedules: ["Segunda e quarta · 15h–16h", "Segunda e quarta · 16h–17h", "Terça e quinta · 09h–10h"], text: "Roteiro, lógica e criação do seu primeiro jogo.", description: "Um espaço para imaginar, criar e programar jogos do zero.", learning: "Roteiro, lógica, programação, design de fases e criação de jogos.", units: ["beira-linha", "sao-pedro"] },
  { id: "informatica18", name: "Introdução à Informática", shortName: "Informática 18+", category: "Informática", professor: "Breno ou Luiz", age: "Adultos · 18–59 anos", days: "Segunda e quarta · Terça e quinta", time: "17h–18h", schedules: ["Segunda e quarta · 17h–18h", "Terça e quinta · 17h–18h"], text: "Ferramentas digitais para estudo, trabalho e autonomia.", description: "Aprenda a usar as principais ferramentas digitais para estudar, trabalhar e organizar sua rotina.", learning: "Word, PowerPoint, Excel e organização de arquivos.", units: ["beira-linha"] },
  { id: "informatica60", name: "Inclusão Digital 60+", shortName: "Inclusão Digital 60+", category: "Inclusão digital", professor: "Breno", age: "60 anos ou mais", days: "Terça e quinta", time: "11h–12h", schedules: ["Terça e quinta · 11h–12h"], text: "Mais autonomia para explorar o mundo digital.", units: ["beira-linha", "sao-pedro"] },
  { id: "musica", name: "Orquestra / Música", shortName: "Orquestra / Música", category: "Cultura", professor: "Edmilson", age: "9–17 anos", days: "Segunda e quarta", time: "14h–15h ou 15h–16h", schedules: ["Segunda e quarta · 14h–15h", "Segunda e quarta · 15h–16h"], text: "Educação musical, escuta e criação coletiva.", units: ["beira-linha", "sao-pedro"] },
];

export const units: Unit[] = [
  { id: "beira-linha", name: "Beira-Linha", slug: "beira-linha", label: "Unidade tradicional", description: "A primeira unidade da Casa, onde a nossa história ganhou espaço, voz e novos caminhos.", cycle: 7, address: "Rua Beira Linha, 329 · Teresópolis · RJ", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Rua+Beira+Linha+329+Teresopolis+RJ", mapEmbedUrl: "https://www.google.com/maps?q=Rua+Beira+Linha,+329,+Teresópolis,+RJ&output=embed", courseIds: courses.filter((course) => course.units.includes("beira-linha")).map((course) => course.id), accent: "rust" },
  { id: "sao-pedro", name: "São Pedro", slug: "sao-pedro", label: "Nova unidade", description: "A Casa da Inovação agora também está em São Pedro, abrindo novas oportunidades para a comunidade.", cycle: 1, address: "Rua São Pedro, nº 191, Loja 01 · São Pedro · Teresópolis/RJ · CEP 25956-280", mapsUrl: "https://www.google.com/maps/search/?api=1&query=Rua+São+Pedro+191+Loja+01+São+Pedro+Teresópolis+RJ+25956-280", mapEmbedUrl: "https://www.google.com/maps?q=Rua+São+Pedro,+191,+Loja+01,+São+Pedro,+Teresópolis,+RJ,+25956-280&output=embed", courseIds: courses.filter((course) => course.units.includes("sao-pedro")).map((course) => course.id), accent: "moss" },
];

export function getUnit(slug: string) { return units.find((unit) => unit.slug === slug); }
export function getCourse(id: string) { return courses.find((course) => course.id === id); }
export function getCoursesForUnit(unitId: UnitId) { return courses.filter((course) => course.units.includes(unitId)); }
